### ISSUE TITLE
Build webinars landing page (page 20 of pdf)

### ISSUE THREAD

**Issue by sbernheim4** [kineticglobal/kinetic-web#98]

**Comment by ldthorne** [comment]
Bryan Jones
@sambernheim @danielthorne3 I made you both managers on the KG youtube channel, so you can access code for embedding the channel. Not sure if it's best to use an iframe or some other option. I'm sure there are multiple ways to do it. You should be able to access all the info needed with manager access to the channel, but I can pull other info as needed.
Aug 31 at 12:01 PM - Reply
BJ
Bryan Jones
Iframe for Google calendar:

<iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showTabs=0&amp;mode=AGENDA&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=kineticglobal.org_dvdepd0hmkvd00lno8jtg1m004%40group.calendar.google.com&amp;color=%23B1440E&amp;ctz=America%2FNew_York" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
Aug 31 at 11:48 AM - Reply
BJ
Bryan Jones
There's a chance you might need some more info from me to embed a youtube channel and a google calendar, just not sure what info exactly. I will take a closer look in the next few days. Let me know if this gets blocked due to lack of info from me.

Also the question forms should be sent to katie.swoap@kineticglobal.org and general@kineticglobal.org

**Comment by ldthorne** [comment]
Bryan Jones
@sambernheim @danielthorne3 I made you both managers on the KG youtube channel, so you can access code for embedding the channel. Not sure if it's best to use an iframe or some other option. I'm sure there are multiple ways to do it. You should be able to access all the info needed with manager access to the channel, but I can pull other info as needed.
Aug 31 at 12:01 PM - Reply
BJ
Bryan Jones
Iframe for Google calendar:

`<iframe src="https://calendar.google.com/calendar/embed?showTitle=0&amp;showNav=0&amp;showDate=0&amp;showTabs=0&amp;mode=AGENDA&amp;height=600&amp;wkst=1&amp;bgcolor=%23FFFFFF&amp;src=kineticglobal.org_dvdepd0hmkvd00lno8jtg1m004%40group.calendar.google.com&amp;color=%23B1440E&amp;ctz=America%2FNew_York" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>`
Aug 31 at 11:48 AM - Reply
BJ
Bryan Jones
There's a chance you might need some more info from me to embed a youtube channel and a google calendar, just not sure what info exactly. I will take a closer look in the next few days. Let me know if this gets blocked due to lack of info from me.

Also the question forms should be sent to katie.swoap@kineticglobal.org and general@kineticglobal.org
